import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, ChevronDown, Cloud, FileText, Mail, MessageSquare, Phone, ShieldCheck, Sparkles, Zap } from 'lucide-react';

const posts = [
  { category: 'Product updates', title: 'Why every Kenyan business needs a reliable SMS channel', date: '09 Oct 2026', excerpt: 'Turn important customer moments into conversations with simple, trackable bulk messaging.', published: true },
  { category: 'Guides', title: 'How to choose a memorable sender ID', date: '02 Oct 2026', excerpt: 'A practical guide to building recognition and trust across Safaricom, Airtel and Telkom.', published: true },
  { category: 'Business growth', title: 'Five campaigns you can automate this week', date: '25 Sep 2026', excerpt: 'Welcome messages, reminders, offers and delivery updates that keep customers close.', published: true },
];

export function PublicLandingPage() {
  const [faq, setFaq] = useState<number | null>(0);
  const [publishedPosts] = useState(() => {
    try {
      const saved = JSON.parse(localStorage.getItem('abancool_content') || 'null') as typeof posts | null;
      return saved?.filter(post => post.published) || posts;
    } catch {
      return posts;
    }
  });
  return (
    <div className="min-h-screen bg-white text-slate-900">
      <div className="bg-[#07133f] text-white text-xs py-2"><div className="max-w-7xl mx-auto px-5 flex justify-between"><span>Garissa, Kenya — serving businesses across Africa</span><span className="hidden sm:block">Sales: 0724 147 910 · Support: 0111 679 286</span></div></div>
      <header className="sticky top-0 z-20 bg-white/95 backdrop-blur border-b border-slate-100"><div className="max-w-7xl mx-auto px-5 h-20 flex items-center justify-between">
        <Link to="/" className="flex items-center gap-3"><span className="w-10 h-10 rounded-xl bg-blue-600 text-white flex items-center justify-center"><Cloud className="w-6 h-6" /></span><span className="text-xl font-extrabold tracking-tight">ABANCOOL</span></Link>
        <nav className="hidden lg:flex items-center gap-8 text-sm font-medium text-slate-600"><a href="#solutions">Solutions</a><a href="#pricing">Pricing</a><a href="#stories">News</a><a href="#faq">FAQ</a></nav>
        <div className="flex items-center gap-3"><Link to="/login" className="hidden sm:block text-sm font-semibold text-slate-600 hover:text-blue-600">Client Area</Link><Link to="/register" className="rounded-full bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-blue-200 hover:bg-blue-700 transition">Start free</Link></div>
      </div></header>

      <main>
        <section className="relative overflow-hidden bg-gradient-to-br from-[#071b8d] via-[#123fe2] to-[#1559ff] text-white"><div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'radial-gradient(#fff 1px, transparent 1px)', backgroundSize: '22px 22px' }} /><div className="relative max-w-7xl mx-auto px-5 py-24 lg:py-32 grid lg:grid-cols-[1.1fr_.9fr] gap-14 items-center">
          <div><p className="uppercase tracking-[.28em] text-xs font-bold text-blue-100">Bulk SMS · Payments · Digital services</p><h1 className="mt-5 text-5xl sm:text-6xl lg:text-7xl font-black leading-[.98] tracking-tight">Reach people.<br /><span className="text-cyan-200">Grow boldly.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-blue-100">Professional bulk SMS for Kenyan businesses, with M-Pesa payments, branded sender IDs and delivery reports that keep every message accountable.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/register" className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-bold text-blue-700 hover:bg-blue-50 transition">Create your account <ArrowRight className="w-4 h-4" /></Link><a href="#solutions" className="inline-flex items-center rounded-full border border-white/30 px-6 py-3.5 font-bold text-white hover:bg-white/10 transition">Explore solutions</a></div><div className="mt-10 flex flex-wrap gap-6 text-sm text-blue-100"><span className="flex items-center gap-2"><Check className="w-4 h-4 text-cyan-200" /> 5 free SMS to start</span><span className="flex items-center gap-2"><Check className="w-4 h-4 text-cyan-200" /> Local M-Pesa checkout</span></div></div>
          <div className="relative"><div className="absolute -inset-8 rounded-full bg-cyan-300/20 blur-3xl" /><div className="relative rounded-3xl border border-white/20 bg-white/10 p-5 shadow-2xl backdrop-blur"><div className="rounded-2xl bg-white p-5 text-slate-900"><div className="flex items-center justify-between"><div><p className="text-xs text-slate-400">Campaign performance</p><p className="mt-1 text-2xl font-black">+42.8%</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-600">This month</span></div><div className="mt-7 flex h-36 items-end gap-3">{[42, 65, 50, 78, 63, 92, 84].map((height, index) => <div key={index} className="flex-1 rounded-t-lg bg-gradient-to-t from-blue-600 to-cyan-300" style={{ height: `${height}%` }} />)}</div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-slate-100 pt-4 text-center"><div><p className="text-lg font-black">98.4%</p><p className="text-[10px] uppercase tracking-wide text-slate-400">Delivered</p></div><div><p className="text-lg font-black">24/7</p><p className="text-[10px] uppercase tracking-wide text-slate-400">Visibility</p></div><div><p className="text-lg font-black">KES 0.80</p><p className="text-[10px] uppercase tracking-wide text-slate-400">From / SMS</p></div></div></div></div></div>
        </div></section>

        <section id="solutions" className="max-w-7xl mx-auto px-5 py-24"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-600">Everything in one place</p><h2 className="mt-3 text-4xl font-black tracking-tight">Tools that move your business forward.</h2><p className="mt-4 text-slate-500 leading-7">From your first welcome message to your thousandth order, ABANCOOL helps you communicate with confidence.</p></div><div className="mt-12 grid md:grid-cols-3 gap-5"><Feature icon={<MessageSquare />} title="Bulk SMS" text="Send targeted campaigns, schedule reminders and track delivery in real time." /><Feature icon={<Sparkles />} title="Sender ID marketplace" text="Apply for a professional branded sender ID across Safaricom, Airtel and Telkom." /><Feature icon={<Zap />} title="M-Pesa payments" text="Collect payments through secure Daraja STK Push and receive instant receipts." /></div></section>

        <section id="pricing" className="bg-slate-50 border-y border-slate-100"><div className="max-w-7xl mx-auto px-5 py-24 grid lg:grid-cols-[.8fr_1.2fr] gap-12 items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-600">Sender ID marketplace</p><h2 className="mt-3 text-4xl font-black tracking-tight">Be remembered in every inbox.</h2><p className="mt-5 text-slate-500 leading-7">Reserve your business name for just <strong className="text-slate-900">KES 7,500</strong> per network. Submit your KRA PIN and business registration certificate, then our team reviews your request within 48 hours.</p><Link to="/register" className="mt-7 inline-flex items-center gap-2 font-bold text-blue-600">Apply for a sender ID <ArrowRight className="w-4 h-4" /></Link></div><div className="grid sm:grid-cols-3 gap-4"><Network name="Safaricom" price="7,500" color="bg-emerald-500" /><Network name="Airtel" price="7,500" color="bg-red-500" /><Network name="Telkom" price="7,500" color="bg-orange-500" /></div></div></section>

        <section id="stories" className="max-w-7xl mx-auto px-5 py-24"><div className="flex items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-600">From the newsroom</p><h2 className="mt-3 text-4xl font-black tracking-tight">Ideas for growing smarter.</h2></div><a href="#stories" className="hidden sm:flex items-center gap-2 text-sm font-bold text-blue-600">View all news <ArrowRight className="w-4 h-4" /></a></div><div className="mt-10 grid md:grid-cols-3 gap-6">{publishedPosts.map(post => <article key={post.title} className="group rounded-2xl border border-slate-200 p-6 hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-100 transition"><div className="w-11 h-11 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center"><FileText className="w-5 h-5" /></div><p className="mt-8 text-xs font-bold uppercase tracking-widest text-blue-600">{post.category}</p><h3 className="mt-3 text-xl font-black leading-snug group-hover:text-blue-600">{post.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{post.excerpt}</p><p className="mt-6 text-xs font-semibold text-slate-400">{post.date}</p></article>)}</div></section>

        <section id="faq" className="bg-[#07133f] text-white"><div className="max-w-4xl mx-auto px-5 py-24"><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan-300">Questions, answered</p><h2 className="mt-3 text-4xl font-black">Make the next message count.</h2><div className="mt-10 divide-y divide-white/15">{['How soon can I start sending SMS?', 'What documents do I need for a sender ID?', 'How does M-Pesa STK Push work?'].map((question, index) => <div key={question} className="py-5"><button className="w-full flex items-center justify-between text-left font-bold" onClick={() => setFaq(faq === index ? null : index)}>{question}<ChevronDown className={`w-5 h-5 transition ${faq === index ? 'rotate-180 text-cyan-300' : ''}`} /></button>{faq === index && <p className="mt-3 max-w-2xl text-sm leading-7 text-blue-100">Create an account, choose a package and complete your checkout. Sender ID applications need your KRA PIN certificate, business registration certificate and an 11-character name.</p>}</div>)}</div></div></section>
      </main>
      <footer className="bg-[#050d2c] text-blue-100"><div className="max-w-7xl mx-auto px-5 py-10 flex flex-col md:flex-row justify-between gap-6 text-sm"><div><div className="flex items-center gap-2 font-black text-white"><Cloud className="w-5 h-5 text-cyan-300" /> ABANCOOL</div><p className="mt-3 text-blue-300">Communications that grow with you.</p></div><div className="flex flex-wrap gap-5"><span className="flex items-center gap-2"><Mail className="w-4 h-4" /> support@abancool.com</span><span className="flex items-center gap-2"><Phone className="w-4 h-4" /> 0111 679 286</span><span className="flex items-center gap-2"><ShieldCheck className="w-4 h-4" /> Secure payments</span></div></div></footer>
    </div>
  );
}

function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="rounded-2xl border border-slate-200 p-7 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-50 transition"><div className="w-12 h-12 rounded-xl bg-blue-600 text-white flex items-center justify-center">{icon}</div><h3 className="mt-7 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{text}</p></div>; }
function Network({ name, price, color }: { name: string; price: string; color: string }) { return <div className="rounded-2xl bg-white p-6 shadow-sm border border-slate-200"><div className={`w-10 h-10 rounded-xl ${color} mb-8`} /><p className="font-black">{name}</p><p className="mt-2 text-2xl font-black">KES {price}</p><p className="mt-1 text-xs text-slate-400">one-time application</p><Link to="/login" className="mt-6 block text-sm font-bold text-blue-600">Apply now <ArrowRight className="inline w-4 h-4" /></Link></div>; }
